# Autogenerated by `bun2nix`, editing manually is not recommended
#
# Set of Bun packages to install
#
# Consume this with `fetchBunDeps` (recommended)
# or `pkgs.callPackage` if you wish to handle
# it manually.
{
  copyPathToStore,
  fetchFromGitHub,
  fetchgit,
  fetchurl,
  ...
}:
{
  "@knadh/oat@0.4.2" = fetchurl {
    url = "https://registry.npmjs.org/@knadh/oat/-/oat-0.4.2.tgz";
    hash = "sha512-+mQnuJP11TKasrtiHKwyrFLXFyb1hxmKzbLALBjUlJHbS2bPV+YPkGN9/5QNRU/3nvM7zZHRVqtWaASFaFC3IA==";
  };
  "@someshkar/oat-chips@1.0.1" = fetchurl {
    url = "https://registry.npmjs.org/@someshkar/oat-chips/-/oat-chips-1.0.1.tgz";
    hash = "sha512-CSX1deVlTX7Kgh7Kd8nJw0oATi7hQEnBx4aLvKE9wsLzM2kIvj8IKkQTw3yt8gIzb/Q0Hng4Kkg724xZCVaZEg==";
  };
  "bun2nix@2.0.8" = fetchurl {
    url = "https://registry.npmjs.org/bun2nix/-/bun2nix-2.0.8.tgz";
    hash = "sha512-pwq35hA81X1Kjsi5Xo69Aii9aY3zZHhWXwqF1QRz/uB35KzKbwJZ16WrhadiG9/T6bjOsRrPZtzuAyqmlXopLw==";
  };
  "htm@3.1.1" = fetchurl {
    url = "https://registry.npmjs.org/htm/-/htm-3.1.1.tgz";
    hash = "sha512-983Vyg8NwUE7JkZ6NmOqpCZ+sh1bKv2iYTlUkzlWmA5JD2acKoxd4KVxbMmxX/85mtfdnDmTFoNKcg5DGAvxNQ==";
  };
  "mri@1.2.0" = fetchurl {
    url = "https://registry.npmjs.org/mri/-/mri-1.2.0.tgz";
    hash = "sha512-tzzskb3bG8LvYGFF/mDTpq3jpI6Q9wc3LEmBaghu+DdCssd1FakN7Bc0hVNmEyGq1bq3RgfkCb3cmQLpNPOroA==";
  };
  "preact@10.29.0" = fetchurl {
    url = "https://registry.npmjs.org/preact/-/preact-10.29.0.tgz";
    hash = "sha512-wSAGyk2bYR1c7t3SZ3jHcM6xy0lcBcDel6lODcs9ME6Th++Dx2KU+6D3HD8wMMKGA8Wpw7OMd3/4RGzYRpzwRg==";
  };
  "sade@1.8.1" = fetchurl {
    url = "https://registry.npmjs.org/sade/-/sade-1.8.1.tgz";
    hash = "sha512-xal3CZX1Xlo/k4ApwCFrHVACi9fBqJ7V+mwhBsuf/1IOKbBy098Fex+Wa/5QMubw09pSZ/u8EY8PWgevJsXp1A==";
  };
}
